## to use this executor use local-postman/collection script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: postman-executor
spec:
  uri: http://testkube-postman-executor:8082
  executor_type: rest
  types:
    - postman/collection

---
## to use this executor use local-curl/test script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: curl-executor
spec:
  uri: http://testkube-curl-executor:8083
  executor_type: rest
  types:
    - curl/test

---
## to use this executor use local-cypress/project script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: cypress-executor
spec:
  uri: http://testkube-cypress-executor:8084
  executor_type: rest
  types:
    - cypress/project

---
## to use this executor use local-postman/collection script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: local-postman
spec:
  uri: http://localhost:8082
  executor_type: rest
  types:
    - local-postman/collection

---
## to use this executor use local-curl/test script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: local-curl
spec:
  uri: http://localhost:8083
  executor_type: rest
  types:
    - local-curl/test

---
## to use this executor use local-cypress/project script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: local-cypress
spec:
  uri: http://localhost:8084
  executor_type: rest
  types:
    - local-cypress/project

---
# you can create new script with type postman-job/collection to run it on top of this executor
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: postman-job
spec:
  image: kubeshop/testkube-postman-executor
  executor_type: job
  types:
    - postman-job/collection

---
## to use this executor use local-cypress/project script type when creating script CR
apiVersion: executor.testkube.io/v2
kind: Executor
metadata:
  name: jmeter-distributed-executor
spec:
  uri: http://testkube-cypress-executor:8084
  executor_type: job
  types:
    - test/jmeterd
  slaves:
    image: kubeshop/testkube-jmeterd-slave